--liquibase formatted sql

--changeset somestrevka:002-create-skill
CREATE TABLE skill
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

--changeset somestrevka:003-create-project
CREATE TABLE project
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

--changeset somestrevka:004-create-engineer-skill
CREATE TABLE engineer_skill
(
    engineer_id INT    NOT NULL REFERENCES software_engineer (id) ON DELETE CASCADE,
    skill_id    BIGINT NOT NULL REFERENCES skill (id),
    PRIMARY KEY (engineer_id, skill_id)
);

--changeset somestrevka:005-create-project-requirement
CREATE TABLE project_requirement
(
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    skill_id   BIGINT NOT NULL REFERENCES skill (id),
    PRIMARY KEY (project_id, skill_id)
);

--changeset somestrevka:006-drop-tech-stack
ALTER TABLE software_engineer DROP COLUMN tech_stack;