--liquibase formatted sql

--changeset somestrevka:008-create-user
CREATE TABLE app_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
)